#!/bin/sh

OLDPATH=$PATH; PATH=".:..:$(dirname $0):$PATH"; . _spmon_lib; PATH=$OLDPATH

# Input: LOGIN, PASSWORD
# Output: number of days of Internet connectivity left

request -O $TM/1.html https://stat.netbynet.ru/
request -O $TM/2.html --post-data="login=$LOGIN&password=$PASSWORD" https://stat.netbynet.ru/

grab 'До окончания текущего расчетного периода осталось (\d+) дн' 1 <$TM/2.html
