#!/bin/sh

OLDPATH=$PATH; PATH=".:..:$PATH"; . _spmon_lib; PATH=$OLDPATH

# Input: LOGIN, PASSWORD
# Output: account balance

request -O $TM/1.html 'https://login.skype.com/account/login-form?return_url=https://secure.skype.com/account/login'
request -O $TM/2.html --post-data="username=$LOGIN&password=$PASSWORD" https://login.skype.com/account/login-form

# <span id="balanceAmount"><span class='ccy'>&#36;</span>12.34</span>

sed -ne '/<span id="balanceAmount">/ { s/^\s*<span id="balanceAmount">.*>\([0-9.]*\)<.*$/\1/; p }' <$TM/2.html
