#!/bin/sh

OLDPATH=$PATH; PATH=".:..:$(dirname $0):$PATH"; . _spmon_lib; PATH=$OLDPATH

# Input: LOGIN, PASSWORD
# Output: account balance

request -O $TM/1.html 'https://login.skype.com/account/login-form?return_url=https://secure.skype.com/account/login'
request -O $TM/2.html --post-data="username=$LOGIN&password=$PASSWORD" https://login.skype.com/account/login-form

# <span id="balanceAmount"><span class='ccy'>&#36;</span>12.34</span>

grab '<span id="balanceAmount">.*>([0-9.]*)<' 1 <$TM/2.html
