#!/bin/sh -e

OLDPATH=$PATH; PATH=".:..:$(dirname $0):$PATH"; . _spmon_lib; PATH=$OLDPATH

# Input: LOGIN, PASSWORD
# Output: account balance

UA='Mozilla/5.0 (Linux; U; Android 2.2; en-us; Desire_A8181 Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1'

request -O $TM/1.html https://moscowsg.megafon.ru/
request -O $TM/2.html --post-data="MOBILE_MODE=AUTH&LOGIN=$LOGIN&PASSWORD=$PASSWORD" https://moscowsg.megafon.ru/ps/scc/mobile/

# <span id="statusbalance"><span class="balance_good">&#1058;&#1077;&#1082;&#1091;&#1097;&#1080;&#1081; &#1073;&#1072;&#1083;&#1072;&#1085;&#1089;: 123.45 &#1088;&#1091;&#1073;.</span></span>

sed -ne '/<span id="statusbalance">/ { s,^<span id="statusbalance">.*: \([0-9.-]*\) &#1088;&#1091;&#1073;.</span></span>$,\1,; p }' <$TM/2.html
