#!/bin/sh

OLDPATH=$PATH; PATH=".:..:$PATH"; . _spmon_lib; PATH=$OLDPATH

# Input: LOGIN, PASSWORD
# Output: account balance

request -O $TM/1.html http://www.sipnet.ru/
request -O $TM/2.html --post-data="CabinetAction=login&Name=$LOGIN&Password=$PASSWORD" https://customer.sipnet.ru/cabinet/

#         <div>12.34&nbsp;<span style="font-size: 80%">y.e.</span></div>

sed -ne '/<span style="font-size: 80%">y.e.</ { s,^\s*<div>\([0-9.]*\)&nbsp;<span style="font-size: 80%">y.e.</span></div>\s*$,\1,; p }' <$TM/2.html
