#!/bin/sh

OLDPATH=$PATH; PATH=".:..:$PATH"; . _spmon_lib; PATH=$OLDPATH

# Input: LOGIN, PASSWORD
# Output: account balance

request -O $TM/1.html http://wap.w1.ru

ACTION=$(cat $TM/1.html | sed -ne '/action=/ { s/^.*action="\(.*\)".*$/\1/; p }')
VIEWSTATE=$(cat $TM/1.html | sed -ne '/__VIEWSTATE/ { s/^.*value="\(.*\)".*$/\1/; p }')

request -O $TM/2.html --post-data="__VIEWSTATE=$VIEWSTATE&tbLogin=$LOGIN&tbPassword=$PASSWORD&bcOpenSession=Enter" "http://wap.w1.ru/$ACTION"

# <font face="Arial"><b><a href="balance.aspx"> [123 RUB]</a></b></font></div></font><font face="Verdana"></td>

sed -ne '/<a href="balance.aspx">/ { s/^.*<a href="balance.aspx">\s*\[\s*\([0-9.]*\)\s*RUB\]\s*<\/a>.*$/\1/; p }' <$TM/2.html
