#!/bin/sh

# Input: LOGIN, PASSWORD
# Output: account balance

exit_handler()
{
	local rc=$?
	trap - EXIT
	rm -f $TM/1.html $TM/2.html $TM/cookies.txt
	rmdir $TM
	exit $rc
}

TM=$(mktemp -d)
trap exit_handler HUP PIPE INT QUIT TERM EXIT

UA='Mozilla/5.0 (Linux; U; Android 2.2; en-us; Desire_A8181 Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1'

COOKIE_FILE=$TM/cookies.txt

request()
{
	wget \
		--user-agent="$UA" \
		--load-cookies $COOKIE_FILE \
		--save-cookies $COOKIE_FILE \
		--keep-session-cookies \
		--quiet \
		$@
}

request -O $TM/1.html 'https://ihelper.mts.ru/SELFCAREPDA/Security.mvc/LogOn?returnLink=http%3A%2F%2Fihelper.mts.ru%3A8083%2FSELFCAREPDA%2FHome.mvc'
request -O $TM/2.html --post-data="username=$LOGIN&password=$PASSWORD" 'https://ihelper.mts.ru/SELFCAREPDA/Security.mvc/LogOn?returnLink=http%3A%2F%2Fihelper.mts.ru%3A8083%2FSELFCAREPDA%2FHome.mvc'

#                         <br/>Баланс: <strong><strong>123.45</strong> руб.</strong>

sed -ne '/<br\/>Баланс:/ { s,.*>\([0-9.]*\)</.*$,\1,; p }' <$TM/2.html
